### ISSUE TITLE
Only Unlock and Lock are possible

### ISSUE THREAD

**Issue by AV-HAUSER** [mikewoudenberg/homeassistant-loqed#11]
After installing I got a lock device which has only **Lock** and **Unlock** controls. I am missing the **Open** control. I have a fixed doorknob. Is there a setting somewhere where I can set this?

**Comment by mikewoudenberg** [comment]
Hey this is because of the choice of Home Assistant to not show the `open` button on a lock entity. You can create a separate button that calls the service `lock.open` (See https://www.home-assistant.io/integrations/lock/#use-the-services) with the entity Id of your lock to get that functionality

**Comment by AV-HAUSER** [comment]
He Mike It works. Thanks for your help
