### ISSUE TITLE
Status doesn't change 

### ISSUE THREAD

**Issue by Dutchy-79** [mikewoudenberg/homeassistant-loqed#13]
The status doesn't change, I locked the door and it still shows unlocked.

![Screenshot_20230629_074605_Home Assistant](https://github.com/mikewoudenberg/homeassistant-loqed/assets/22749572/d6a77e63-c4fb-4672-9d5a-f77b0b0a76fc)
![Screenshot_20230629_074611_Home Assistant](https://github.com/mikewoudenberg/homeassistant-loqed/assets/22749572/05876961-244c-4982-b9d9-660a9f48d626)

**Comment by mikewoudenberg** [comment]
Real time updates depend on the webhook functionality of the LOQED bridge. Could you check in https://app.loqed.com what URL got registered as webhook and whether that is reachable from the bridge?

**Comment by Dutchy-79** [comment]
If pressed web api status test it answers with
id":"DONTKNOWIFTGISISSECRET","bolt_state_numeric":2,"bolt_state":"day_lock","lock_online":1,"bridge_online":1,"battery_percentage":76,"battery_type_numeric":1,"battery

**Comment by mikewoudenberg** [comment]
That is the response of the bridge's status api (http://<yourbridgeip>/status). Go to https://app.loqed.com/API-Config/index.php?page=webhook-list 
and check the add/delete webhooks screen.
![Screenshot 2023-06-29 at 15 06 36](https://github.com/mikewoudenberg/homeassistant-loqed/assets/5583336/325950fd-fb92-4fdb-ac9e-e65cdc7b3920)

**Comment by Dutchy-79** [comment]
![Screenshot_20230629_152627_Chrome](https://github.com/mikewoudenberg/homeassistant-loqed/assets/22749572/1cb100cf-61b5-41c4-9f81-58084ecb5666)

**Comment by mikewoudenberg** [comment]
Did you perform the thing noted by the "Important" note? Because I don't see any webhooks.

**Comment by Dutchy-79** [comment]
I can't find a "important note" must have missed that part.

**Comment by mikewoudenberg** [comment]
It's in your latest screenshot. "Important: please disbable...."

**Comment by Dutchy-79** [comment]
🙄😅

**Comment by Dutchy-79** [comment]
Should I delete and reinstall?

![Uploading Screenshot_20230630_083718_Chrome.png…]()

**Comment by mikewoudenberg** [comment]
Your screenshot failed to upload. Delete and reinstall is always an optino, but if for some reason I don't understand the webhook gets setup with the wrong URL it won't help.

**Comment by Dutchy-79** [comment]
![Screenshot_20230630_083718_Chrome](https://github.com/mikewoudenberg/homeassistant-loqed/assets/22749572/5ffe71d8-210e-4ffb-a8dd-2ce54fe0e382)
Nog een poging dan.

**Comment by mikewoudenberg** [comment]
Could you turn on debug logging for the integration? It should then log which webhook URL it will use, maybe we an find it out that way. enabling debug logging is described here: https://github.com/mikewoudenberg/homeassistant-loqed/issues/12#issuecomment-1609558053

**Comment by Dutchy-79** [comment]
It's directed to a old duckdns link
[custom_components.loqed.coordinator] Webhook URL: https://MYOLD.duckdns.org:8123/api/webhook/47878b12b650ec7e383a858e42bd0d4cbacd49a02dc0f190a3a67fc2d946b257
2023-06-30 15:47:15.139 ERROR (SyncWorker_0) [pymodbus.logging] Connection to (192.168.1.219, 1502) failed: timed out
2023-06-30 15:47:18.596 DEBUG (MainThread) [custom_components.loqed.coordinator] Finished fetching Loqed sensors data in 0.748 seconds (success: True)

**Comment by mikewoudenberg** [comment]
It gets that URL from Settings -> System -> Network -> Home Assistant URL. If you change it you should restart Home Assistant.

**Comment by Dutchy-79** [comment]
That did it, now I have webhooks and ✅

![Screenshot_20230630_173159_Chrome](https://github.com/mikewoudenberg/homeassistant-loqed/assets/22749572/ba7afd35-3563-477e-8297-5f4f91e5f97e)

And there's status change

![Screenshot_20230630_174624_Home Assistant](https://github.com/mikewoudenberg/homeassistant-loqed/assets/22749572/1ce393b5-5b09-4461-a44e-e236f650d38d)

Ty very much for the patience to get me there

**Comment by mikewoudenberg** [comment]
Glad I could help out :)

**Comment by jmfargas** [comment]
I have the same problem. I can lock, unlock and open the door from HASS, but the state is not updated. It only updates it if I reload the integration.

What I can see, though, in the webhooks is the one point to the Loqed hub IP, but not HASS. I don't know if this is the problem? Whether I should add a webhook for HASS?
<img width="2680" height="484" alt="Image" src="https://github.com/user-attachments/assets/6d1b2781-aa7b-4bfa-9a7c-f9acc6d131c4" />

I tried to disable "Block insecure private network requests" from "chrome://flags/#block-insecure-private-network-requests", but it's not there? I cannot find it? What can I do? Could you please help me? Many thanks!

**Comment by jmfargas** [comment]
You need to use "Local Network Access Checks" in the new Chrome version...

**Comment by mikewoudenberg** [comment]
You also need to click on the Add/Delete webhooks button to see the actualy registered webhooks. You also need to not raise this here, as this is just a development repo. The Loqed integration is an official part of Home Assistant so you should report any issues there.
