### ISSUE TITLE
Difference HA component and this custom component

### ISSUE THREAD

**Issue by ridderr** [mikewoudenberg/homeassistant-loqed#14]
Hi Mike, Great you continue the work from cpolhout. 
This morning i noticed that HA 2023.7.0b0 now has included LOQED in the release. What is the difference between both implementations? I noticed your name in the sources, but I do also see that the HA implementation is not reporting on battery levels.

**Comment by mikewoudenberg** [comment]
This will become the beta testing version of the core plugin. As per the rules of Home Assistant I only added the `lock` platform on the first PR. I'll add the battery sensor shortly (as I can simply reuse the code from this repository)

**Comment by ridderr** [comment]
Many thanks, good work
