### ISSUE TITLE
readme not complete

### ISSUE THREAD

**Issue by nieq-oh** [mikewoudenberg/homeassistant-loqed#2]
I tried to add loqed to my homeassistant. 
Via HACS it's not available so I did it manuely.
Adding via integrations is not a problem but the readme ends with copying code.
I added the code to a .json file and include it to my configuration, but when I entered the credentials (a made up name and the key and token) but I ended up with a non working website.

**Comment by mikewoudenberg** [comment]
Hey thanks for reaching out. This repository is not really meant for production use. I'm experimenting with things I merge into the actual PR on hoome_assistant over here. Currently I'm experimenting with replacing this copy step by an Oauth step hopefully simplifying the setup procedure. For now you're best off following the guide on the Loqed website unfortunately
