### ISSUE TITLE
Why using oauth 

### ISSUE THREAD

**Issue by fierland** [mikewoudenberg/homeassistant-loqed#3]
Hi Mike,

Just a question why did you use oauth for this implementation. Will that not make the implementation dependent on the internet to use, or is the internet only needed during config ?

Thanks,
Frank

**Comment by mikewoudenberg** [comment]
It was suggested by the maintainers of home assistant, as improvement over the configuration step that involved copy pasting. Internet connectivity is only needed for the setup step. After that it communicates with the bridge directly.

**Comment by fierland** [comment]
Ok clear. Only problem is that you have to contact loqed to get the login info… was hoping to test your code as I think the original code to integrate is not very good and it looks as it is not really developed anymore…


Sincerely yours,
Frank van Ierland
06-21391053

________________________________
Van: Mike Woudenberg ***@***.***>
Verzonden: Friday, December 23, 2022 7:29:39 PM
Aan: mikewoudenberg/homeassistant-loqed ***@***.***>
CC: Frank van Ierland ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mikewoudenberg/homeassistant-loqed] Why using oauth (Issue #3)


It was suggested by the maintainers of home assistant, as improvement over the configuration step that involved copy pasting. Internet connectivity is only needed for the setup step. After that it communicates with the bridge directly.

**Comment by mikewoudenberg** [comment]
We're currently working on a way for you to create the login credentials yourself. So it'll be self service and you don't need Loqed support to set this up. It'll work similar to  the Google integration for example.

The original code is no longer maintained I think, but I'm still using parts of that setup.

**Comment by fierland** [comment]
Ok tested it and is now working. :-)  One other question do you have a plan/overview of coming changes and additions to this integration. I don't mind contributing but would be a waste of time to work on the same things...

**Comment by fierland** [comment]
Ok tested it and is now working. :-)  One other question do you have a plan/overview of coming changes and additions to this integration. I don't mind contributiong but would be a waste of time to work on the same things...

**Comment by fierland** [comment]
Ok thanks. For me its about the missing status information which this integration not yet provides. Like how the device was triggerd etc.
I use the locks to switch my alarm (alarmo) so its verry relevant how the lock was activated (if on a authorized way from outside -> switch alarm off, if manual from inside it can be a burglar 😊 so don’t switch off. I had this working with the cpolhout integration (with some changes in api (does not keep last event_type causing the change of state) and the integration itself.

Van: Mike Woudenberg ***@***.***>
Verzonden: Wednesday, 18 January 2023 17:01
Aan: mikewoudenberg/homeassistant-loqed ***@***.***>
CC: Frank van Ierland ***@***.***>; State change ***@***.***>
Onderwerp: Re: [mikewoudenberg/homeassistant-loqed] Why using oauth (Issue #3)


We're currently focused on getting the Official integration landed after which it'll be made to be on par with this one. After that I'd like to add some configuration options to the device in home assistat as well so you can trigger "touwtje uit de deur modus from HA. This would require some more work on the API though

**Comment by mikewoudenberg** [comment]
> Ok thanks. For me its about the missing status information which this integration not yet provides. Like how the device was triggerd etc. I use the locks to switch my alarm (alarmo) so its verry relevant how the lock was activated (if on a authorized way from outside -> switch alarm off, if manual from inside it can be a burglar 😊 so don’t switch off. I had this working with the cpolhout integration (with some changes in api (does not keep last event_type causing the change of state) and the integration itself. 

You could open a pull request on the loqedapi repository that we could review to make sure we're not breaking the official integration and then tack it on the pr and this custom component. Interesting use case :)

**Comment by mikewoudenberg** [comment]
> Oh and i tested it with 2 locks, which works 😊. Would be nice however to name the lock during config …

My favourite route would be to receive the name it has in the loqed app so you would recognize it immediately. After setting it up you can of course always change it in home assistant

**Comment by mikewoudenberg** [comment]
Just had a look at the PR you openend a while ago on the LoqedAPI repo. Can't that use case be achieved with the current state of the integration? The  `changed_by` attribute of the lock entity is updated when the lock is both moving to a state and when it completed the transition. This seems like all the info you need for the alarm.

**Comment by fierland** [comment]
You probably can but would be much more complex is hass as you need to capture the state during the unlocking/locking event and after a successful lock/unlock check that state. The lock/unlock can still fail so you cannot yet make an action during the unlocking/locking event. So it would be much easier to capture that event an store it in the api (it is just a very small change).

From: Mike Woudenberg ***@***.***>
Date: Thursday, 19 January 2023 at 21:06
To: mikewoudenberg/homeassistant-loqed ***@***.***>
Cc: Frank van Ierland ***@***.***>, State change ***@***.***>
Subject: Re: [mikewoudenberg/homeassistant-loqed] Why using oauth (Issue #3)

Just had a look at the PR you openend a while ago on the LoqedAPI repo. Can't that use case be achieved with the current state of the integration? The changed_by attribute of the lock entity is updated when the lock is both moving to a state and when it completed the transition. This seems like all the info you need for the alarm.
