### ISSUE TITLE
The client id supplied is invalid

### ISSUE THREAD

**Issue by remko-key** [mikewoudenberg/homeassistant-loqed#5]
Hey Mike,
Thanks for the good work. I have one issue after the callback in the last step off the process. Looks like my oauth client_id=1 is not accepted but where can I change this client_id? 

https://app.loqed.com/API/integration_oauth3/redirect_back.php?response_type=code&client_id=1&redirect_uri=https%3A%2F%2Fmy.home-assistant.io%2Fredirect%2Foauth&state=xxxx

`{
  "error": "invalid_client",
  "error_description": "The client id supplied is invalid"
}`

**Comment by mikewoudenberg** [comment]
Hey Remko,

currently the client id and client secret are both hardcoded to `homeassistant`. We expect the self management of these parameters to be available shortly.

**Comment by Kopernikus1979** [comment]
Hi,

Ok thx, got same problem.
So to make it work have to set client id and the password to homeassistant ?

**Comment by mikewoudenberg** [comment]
> 

For now, yes

**Comment by steef84** [comment]
Hi there, I might be overlooking, but I cannot find where to change client id and secret in the LOQED web app.

**Comment by mikewoudenberg** [comment]
You cannot change them in the loqed app. They are still hardcoded as mentioned in https://github.com/mikewoudenberg/homeassistant-loqed/issues/5#issuecomment-1376838976

**Comment by steef84** [comment]
Ok I'm done then. Tried your install instructions but cannot get past error The client id supplied is invalid.

**Comment by mikewoudenberg** [comment]
> Ok I'm done then. Tried your install instructions but cannot get past error The client id supplied is invalid.

Only thing I can think of is removing the application credentials for loqed and adding them again with the hardcoded value. Otherwise I'm out of options

**Comment by steef84** [comment]
Just tried again. now presenting this error
```
Notice: Undefined index: local_key_id in /var/www/app.loqed.com/API/integration_oauth3/redirect_back.php on line 37
No lock_id or local_key_id set
```

**Comment by dwainscheeren** [comment]
I've got the same problem. Can't get it to work.

**Comment by mikewoudenberg** [comment]
This looks like an issue in creating a new API key. Could you try to create a new API key via the LOQED webapp before you start the flow? This way you can select an existing API key in the OAuth flow.

**Comment by pierre-oord** [comment]
> Just tried again. now presenting this error
> 
> ```
> Notice: Undefined index: local_key_id in /var/www/app.loqed.com/API/integration_oauth3/redirect_back.php on line 37
> No lock_id or local_key_id set
> ```

This issue has been solved. Soon users will be able to create a personal OAuth login themselves, and this temporary endpoint will be removed. In the meantime, this endpoint provides OAuth functionality for HASS with the username 'homeassistant' and password 'homeassistant'.
