### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by nieq-oh** [mikewoudenberg/homeassistant-loqed#6]
Hi, I was wondering if there will be a working version of a Loqed integration soon.
Bought my lock 1,5 years ago. On the website there was (and still is) a message Loqed will be working soon with home assistant. At the moment there is still nothing, but this was the most important function while selecting a smart lock. 
Now I want to buy a second lock for another door, but I'm not sure if I'm going to buy a Loqed or 2 of another brand and selling the Loqed. Any idea's how long it will take or how to get this one working? You talk about hardcoding the client id to HA, but where? it's all very unclear.

**Comment by mikewoudenberg** [comment]
Hi nieq-oh. Unfortunately we are not able to influence the actual adoption of our integration into home assistant. We've ticked all the required boxes but for some nreason the Pull Request still doesn't get merged. I've asked multiple times what I can do to speed things along, but to no avail. 

The hardcoded clientId and secret are a temporary solution until a functionality for creating these pairs comes available in the Loqed webapp. The hardcoded value for both is currently `homeassistant`

**Comment by nieq-oh** [comment]
Ok thanks for your fast reply. But how can I make it work with the hardcoded values.. where do I have to fill this in to make it work?

**Comment by mikewoudenberg** [comment]
Install this custom component repository via [HACS](https://hacs.xyz/) Add Application Credentials for Loqed  via Settings -> Devices & services -> Three dots in the top right and select Application Credentials. Select the Loqed integration, give it a name and provided the value I just gave you and store the credential. Now when you restart home assistant it should discover your lock.
