### ISSUE TITLE
LOQED.com Web App PI layout has changed

### ISSUE THREAD

**Issue by davy932** [mikewoudenberg/homeassistant-loqed#7]
Hi,

The Terminology and layout of the API creation screen has changed.
The Intergration asks for OAuth Client ID and OAuth Client Secret.
The App now presents Lock ID, Local Key ID, Key & Token.

Which of these should be used for Client ID / Secret

Thanks

![2023-06-15 10_34_17-LOQED Web App](https://github.com/mikewoudenberg/homeassistant-loqed/assets/35080535/4dbe6e56-fb15-4fb3-8481-deb0e0b90b51)

(Note, this API is now deleted for security)

**Comment by thedutchrockstar** [comment]
Application credentials are hardwired to homeassistant at the moment.
So for both ID and Secret you have to use `homeassistant`
I believe they are still working on OATH credentials.

PS you can add the credentials manually by going to integrations clicking on the three dots and selecting "appliation credentials".

**Comment by davy932** [comment]
WINNER!! Thankyou On 15 Jun 2023, at 13:29, Vincent ***@***.***> wrote:﻿
Application credentials are hardwired to homeassistant at the moment.
So for both ID and Secret you have to use homeassistant
I believe they are still working on OATH credentials.
PS you can add the credentials manually by going to integrations clicking on the three dots and selecting "appliation credentials".

**Comment by thedutchrockstar** [comment]
Perfect @mikewoudenberg I think this one can be closed aswell.

**Comment by mikewoudenberg** [comment]
Thanks for helping out :)
