### ISSUE TITLE
How to reinstall after wrong OAth?

### ISSUE THREAD

**Issue by HFeenstra** [mikewoudenberg/homeassistant-loqed#8]
Hello, installed your custom integration but enter wrong OAth client and id.
(Should have been the word homeassistant)

Keep getting the prompt:
{"error":"invalid_client","error_description":"The client id supplied is invalid"}

So I removed completely integration in HACS restarted Home Assistant and reinstalled the integration, rebooted Home Assistant and do get same prompt. 

I just want to enter the OAth info the word: homeassistant. But now am stuck. Can’t get it working. What do I do wrong??

**Comment by HFeenstra** [comment]
I also removed the complete custom repository but still it prompts to open the website. 

How can I re enter the OAth info? So I can use the word homeassistant instead?

**Comment by mikewoudenberg** [comment]
Hi, if you've entered the wrong application credentails you'd need to remove both the configured integration and the accompanying application credentials. You can do this by going to settings -> application credentials and then tapping on the triple dot menu to the far right. From there select application credentials and delte the LOQED one. 

BTW, IIRC it should ask you to remove the application credentials once you remove the last integrattion using them, but I could be wrong.
<img width="260" alt="Screenshot 2023-06-16 at 07 35 21" src="https://github.com/mikewoudenberg/homeassistant-loqed/assets/5583336/a4fe55f2-0134-4e27-bb10-304861030953">

**Comment by HFeenstra** [comment]
Bedankt ☺️ 

Thanks, did not connect to the application credentials. That cleared it for me. Didn’t even had to reinstall the integration. 

Also appreciate the fact you added a picture to your explanation. 
Wishing you a wonderful day. 
(switch to your integration instead of the cpolhout integration, you reply and maintain it more accurate)

**Comment by mikewoudenberg** [comment]
No worries, I took over all. the hard work cpolhout did, updated his PR towards Home Assistant and bundled the code in this custom component so we can beta test it before it hits general availability.
